meta_product_name: "Art Gallery Project"
meta_title: "Art Gallery Project - make your own exhibition"
meta_description: "This is an app where as a gallerist you're offered a chance to esthetically able to create exhibitions"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
